[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
governance = "7E25FzPJGehHZ6FsqZWrgCPVJ4pk6oDuMgC7EFys9Zpm"
qzl_token = "5YGkyrCgrstFbc2zTTVxNPuAzQrkEvmDp8wu3zGpyh1R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
