[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
governance = "CrJY78Q5h6xFUVD75mGGS5n3ECxWddtGUBYvTYE8pfjb"
qzl_token = "2r7uhBfpqSGMNbCkRFis85QmUoqmQwqyA1CNtiqQXmA3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
# cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
